name: Build Payhip App
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: {distribution: 'zulu', java-version: '17'}
      - uses: subosito/flutter-action@v2
        with: {channel: 'stable'}

      - name: Initialize Project
        run: flutter create --platforms=android,ios --overwrite .

      - name: Force Payhip Code
        run: git checkout lib/main.dart pubspec.yaml

      - name: Inject Android Permissions
        # These lines ensure the app can access the internet in release mode
        run: |
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          sed -i '/<manifest/a \    <uses-permission android:name="android.permission.INTERNET"\/>' $MANIFEST
          sed -i '/<application/a \        android:usesCleartextTraffic="true"' $MANIFEST

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with: {name: payhip-android-app, path: build/app/outputs/flutter-apk/app-release.apk}
